### ISSUE TITLE
关于下载embeddings在stable-diffusion-webui中使用没有生效

### ISSUE THREAD

**Issue by uikino** [wfjsw/danbooru-diffusion-prompt-builder#10]
我在Danbooru 标签超市中下载了luotianyi-v2-66e896.webp放入到了embeddings文件夹中
但是在txt2img中填入tag luotianyi-v2-66e896 生成图片下方描述中没有显示我使用embedding
并且在文件管理器中我能够以将pt视作压缩包打开，但是下载的embedding无法打开识别
而提供的convert-pt-embedding-to-png.ipynb的转换代码实际转换时会发生异常，所以我也无法通过调试逆向了
现在能否提供一个webp还原的脚本，或则方法？

这是web界面
![2022-11-23 23-11-34 创建的截图](https://user-images.githubusercontent.com/12792786/203581325-757c4dc2-d559-46c6-84ea-34ad7b459b5b.png)
这是文件列表
![2022-11-23 23-14-16 创建的截图](https://user-images.githubusercontent.com/12792786/203581856-e9be6892-1cce-428d-a0b4-4ac444c958ae.png)

**Comment by wfjsw** [comment]
文件名不要改，改了就不认了

**Comment by uikino** [comment]
还是不行，文件名为luotianyi-v2-66e896.webp sha256sum 8d07e555d573ef476c251bf1255c0bc0d0984bd6d2cc54a47357ad9ef45f2702
在prompt中输入: luotianyi-v2-66e896或luotianyi-v1还是luotianyi-v2-66e896.webp都是不行。难道要webui启动的时候添加什么option吗？明天再说吧

**Comment by wfjsw** [comment]
看起来要用图片左上角那个 tag。
比较怪，我感觉我每次试的时候结果都不一样，我再仔细看看。

**Comment by wfjsw** [comment]
重新下一份，现在可以用文件名了。

**Comment by uikino** [comment]
还是不行，我将其扩展名修改为bin和pt都不行

![2022-11-24 19-57-53 创建的截图](https://user-images.githubusercontent.com/12792786/203779264-fc972e2f-f74f-4306-ad22-02da1c47e3ad.png)


下面是webui的启动log和txt2img的过程
```
discaz@discaz-usb:~/disk/pool1/stable-diffusion-webui|master⚡ 
⇒  ./webui.sh  --medvram  --deepdanbooru  --xformers

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on discaz user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Python 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Installing requirements for Dreambooth
Installing torch and torchvision

[auto-sd-paint-ext] Attempting auto-update...
[auto-sd-paint-ext] Fetch upstream.
[auto-sd-paint-ext] Pull upstream.

loading Dreambooth reqs from /run/media/discaz/pool1/stable-diffusion-webui/extensions/sd_smartprocess/requirements.txt
Checking Smart Crop requirements.

Launching Web UI with arguments: --medvram --deepdanbooru --xformers
2022-11-24 19:53:08.645327: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-24 19:53:08.820029: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-11-24 19:53:09.620918: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/discaz/.local/lib/python3.10/site-packages/cv2/../../lib64:
2022-11-24 19:53:09.621054: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/discaz/.local/lib/python3.10/site-packages/cv2/../../lib64:
2022-11-24 19:53:09.621076: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [38c1ebe3] from /run/media/discaz/pool1/stable-diffusion-webui/models/Stable-diffusion/Anything-V3.0-pruned-fp16.ckpt
Loading VAE weights from: /run/media/discaz/pool1/stable-diffusion-webui/models/VAE/Anything-V3.0.vae.pt
Applying xformers cross attention optimization.
Model loaded.
Error verifying pickled file from /run/media/discaz/pool1/stable-diffusion-webui/embeddings/amamiya-kokoro-02cce4.pt:
Traceback (most recent call last):
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/safe.py", line 83, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/safe.py", line 98, in check_pt
    unpickler.load()
_pickle.UnpicklingError: unpickling stack underflow

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error loading emedding amamiya-kokoro-02cce4.pt:
Traceback (most recent call last):
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 133, in load_textual_inversion_embeddings
    process_file(fullfn, fn)
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 103, in process_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Error verifying pickled file from /run/media/discaz/pool1/stable-diffusion-webui/embeddings/luotianyi-v2-0c5e7c.bin:
Traceback (most recent call last):
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/safe.py", line 83, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "/usr/lib/python3.10/zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.10/zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/safe.py", line 98, in check_pt
    unpickler.load()
_pickle.UnpicklingError: unpickling stack underflow

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error loading emedding luotianyi-v2-0c5e7c.bin:
Traceback (most recent call last):
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 133, in load_textual_inversion_embeddings
    process_file(fullfn, fn)
  File "/run/media/discaz/pool1/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 103, in process_file
    if 'string_to_param' in data:
TypeError: argument of type 'NoneType' is not iterable

Loaded a total of 111 textual inversion embeddings.
Embeddings: style-torino, rustle, kanata-hololive, 碧蓝档案-美游, 原神-神里, ganyu-genshin-impact, henreader, YiLeiNa, Tashkent, style-KeiginAlumi_A, bronya-zaychik-布洛妮娅·扎伊切克（崩坏3）-konata19-Embeddings-61500, ailixiya-12400, 碧蓝幻想-玛琪拉, amine, 局长, mana-100000, gyn-last, 碧蓝档案-梓, 碧蓝档案-小春, ba-shiroko, style-kedama, style-gbf, taiga-38567, sanna-marin, style-keta, amane-kanata2-42198, million-live-spade-q-style-3k, Usada Pekora, wunei, kase-daiki-46506, kokomi-prompt-珊瑚宫心海-琥鈴琴奏-Embeddings, maodoufu, camonome-55500, kaoming-42600, ohisashiburi-style, chihunhentai2-60000, raita, chara_ark_suzuran-明日方舟铃兰-Fire Ghoscat-Embeddings, gweda-76000, inuyama-muneto-style-nao, hiten-style-nao, ruoyin, gyn1, a1-36400, puno, gyn-great, ailixiya-9300, million-live-spade-q-object-3k, ailixiya-6200, kogecha, 碧蓝航线-小天城, sshly-ori, DSマイル, agm-style-nao, haruhisky-47000, 66e896e95539a5da7a21cfe5c6d9323a4c30ebf9462687a8d5ddf5bf1626e47c, anya-forger, gyn2, kazama-iroha-15895, ayanami, atdan-art, geewhy-60000, Amamiya_Kokoro-天宫心（彩虹社）-Seal_773-Embeddings, million-live-akane-15k, chihunhentai-80000, shiratama, style-donadona, hitokomoru-style-nao, sshly-i2i, 原神-纳西妲, luotianyi_v2-洛天依-Fixing_And_Repairing-Embeddings, raiden shogun-雷电将军-舞晗坤-Embedding-5000, as109-60000, learned_embeds, Kafuu_Chino_Swimwear, ailixiya-15500, lucy-cyberpunk, hiyuki-chan, Amane-Kanata-40500, eru-chitanda-casual, hutao-prompt-胡桃-yarimasune1-Embeddings, satoshi-urushihara-50000, cutesexyrobutts-100000, Ganyu, real xxiii, birgbear-100000, style-as109, ononoimoko, 公主连接-可可萝, agm-60000, myned, yileina, kawaii-girl-plus-style-v1-1, million-live-akane-3k, lasterk-24500, Da-Mao-Banlangen-76500, hanfu-anime-style, shigure-ui-style, ydssx, wlop-style, style-keta-nsfw, mignon-62500, nazuna, cam-100000, as109, e2ui6r, marine, 852style-girl, suisei-hololive, kogatan-shiny, dianniang
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
auto-sd-paint-ext:WARNING: COMMANDLINE_ARGS does not contain --api, API won't be mounted.
File /run/media/discaz/pool1/stable-diffusion-webui/extensions/stable-diffusion-webui-wildcards/wildcards/luotianyi-v2-0c5e7c.txt not found for the __luotianyi-v2-0c5e7c__ wildcard.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:50<00:00,  3.57s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 31/31 [01:36<00:00,  3.11s/it]


```

**Comment by wfjsw** [comment]
webp 的扩展名不要变。

**Comment by uikino** [comment]
没有，我已经删了重试，没有用。本地文件sha256sum 6711547cce19c486205b2df092a669db4327b37b8a3dce77367b3f6f369bc9f7

使用wget 下载验证
```
discaz {~/disk/pool1/stable-diffusion-webui/embeddings}±(master*); greetings, earthling [131.603Mb]$ ☞ wget https://tags.novelai.dev/embeddings/0c/0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp
--2022-11-24 20:16:26--  https://tags.novelai.dev/embeddings/0c/0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp
已载入 CA 证书“/etc/ssl/certs/ca-certificates.crt”
正在连接 192.168.88.2:19641... 已连接。
已发出 Proxy 请求，正在等待回应... 200 OK
长度：248598 (243K) [image/webp]
正在保存至: “0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp”

0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c 100%[=============================================================================================================>] 242.77K  --.-KB/s  用时 0.06s   

2022-11-24 20:16:27 (4.18 MB/s) - 已保存 “0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp” [248598/248598])

discaz {~/disk/pool1/stable-diffusion-webui/embeddings}±(master*); greetings, earthling [131.603Mb]$ ☞ sha256sum 0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp 
6711547cce19c486205b2df092a669db4327b37b8a3dce77367b3f6f369bc9f7  0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp
discaz {~/disk/pool1/stable-diffusion-webui/embeddings}±(master*); greetings, earthling [131.603Mb]$ ☞ 
```

要不要个ssh口子进来，

**Comment by wfjsw** [comment]
刚才修改过之后，现在 Embedding 的 Prompt 已经是文件名了。
可以截图一下 Train > Train 页面下的 Embedding 下拉菜单检查一下。

**Comment by uikino** [comment]
在Train中的Embedding的选项中没有发现对应的luotianyi这个prompt,倒是有一个我不认识。
但我没给任何embedding起过```66e896e95539a5da7a21cfe5c6d9323a4c30ebf9462687a8d5ddf5bf1626e47c``` 这种名称
![2022-11-24 20-28-38 创建的截图](https://user-images.githubusercontent.com/12792786/203784905-91eb9df6-9d97-4972-bbf9-c89d723d312e.png)

**Comment by wfjsw** [comment]
看看你的 Embedding 文件夹，是不是有个文件名叫这东西咯。

**Comment by uikino** [comment]
有类似的，0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp 就是luotianyi-v2-0c5e7c.webp
```
discaz {~/disk/pool1/stable-diffusion-webui/embeddings}±(master*); greetings, earthling [131.603Mb]$ ☞ ll
总计 4.3M
-rw-r--r-- 1 discaz discaz 243K 11月24日 20:16  0c5e7ca3273e15ea090deda19c695858ab7274030a41769a9c74213bc96b4fcd.webp
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:53  852style-girl.bin
-rw-r--r-- 1 discaz discaz  37K 11月13日 03:09  碧蓝档案-美游.pt
-rw-r--r-- 1 discaz discaz  37K 11月13日 03:09  碧蓝档案-小春.pt
-rw-r--r-- 1 discaz discaz  37K 11月13日 03:09  碧蓝档案-梓.pt
-rw-r--r-- 1 discaz discaz  37K 11月13日 03:09  碧蓝航线-小天城.pt
-rw-r--r-- 1 discaz discaz  37K 11月13日 03:09  碧蓝幻想-玛琪拉.pt
-rw-r--r-- 1 discaz discaz  37K 11月13日 03:09  公主连接-可可萝.pt
-rwxrwx--- 1 discaz discaz  70K 10月21日 05:07  局长.bin
-rw-r--r-- 1 discaz discaz  31K 11月13日 03:09  原神-纳西妲.pt
-rw-r--r-- 1 discaz discaz  37K 11月13日 03:09  原神-神里.pt
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  a1-36400.bin
-rw-r--r-- 1 discaz discaz  49K 10月 6日 19:32  agm-60000.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月21日 04:31  agm-style-nao.bin
-rw-r--r-- 1 discaz discaz  37K 11月22日 23:14  ailixiya-12400.pt
-rw-r--r-- 1 discaz discaz  37K 11月22日 23:14  ailixiya-15500.pt
-rw-r--r-- 1 discaz discaz  37K 11月22日 23:14  ailixiya-6200.pt
-rw-r--r-- 1 discaz discaz  37K 11月22日 23:14  ailixiya-9300.pt
-rw-r--r-- 1 discaz discaz 267K 11月12日 04:32  amamiya-kokoro-02cce4.pt
-rw-r--r-- 1 discaz discaz  25K 11月23日 23:35  Amamiya_Kokoro-天宫心（彩虹社）-Seal_773-Embeddings.pt
-rw-r--r-- 1 discaz discaz  25K 10月 6日 19:32  amane-kanata2-42198.bin
-rw-r--r-- 1 discaz discaz  27K 10月 6日 19:32  Amane-Kanata-40500.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:54  amine.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:54  anya-forger.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  as109-60000.bin
-rwxrwx--- 1 discaz discaz  61K 10月21日 04:53  as109.bin
-rw-r--r-- 1 discaz discaz  55K 11月22日 01:06  atdan-art.pt
-rw-r--r-- 1 discaz discaz  25K 11月22日 01:06  ayanami.pt
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:54  ba-shiroko.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  birgbear-100000.bin
-rw-r--r-- 1 discaz discaz  37K 11月23日 23:33  bronya-zaychik-布洛妮娅·扎伊切克（崩坏3）-konata19-Embeddings-61500.pt
-rw-r--r-- 1 discaz discaz  49K 10月 6日 19:32  cam-100000.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  camonome-55500.bin
-rw-r--r-- 1 discaz discaz  31K 11月23日 23:34 'chara_ark_suzuran-明日方舟铃兰-Fire Ghoscat-Embeddings.pt'
-rw-r--r-- 1 discaz discaz  49K 10月 6日 19:32  chihunhentai2-60000.bin
-rw-r--r-- 1 discaz discaz  49K 10月 6日 19:32  chihunhentai-80000.bin
-rw-r--r-- 1 discaz discaz  49K 10月 6日 19:32  cutesexyrobutts-100000.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  Da-Mao-Banlangen-76500.bin
-rw-r--r-- 1 discaz discaz  22K 11月22日 01:06  dianniang.pt
-rwxrwx--- 1 discaz discaz  70K 10月21日 05:08  DSマイル.bin
-rw-r--r-- 1 discaz discaz 5.1K 10月20日 01:50  e2ui6r.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:55  eru-chitanda-casual.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月21日 04:34  Ganyu.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:56  ganyu-genshin-impact.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  geewhy-60000.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  gweda-76000.bin
-rw-r--r-- 1 discaz discaz  25K 11月22日 23:14  gyn1.pt
-rw-r--r-- 1 discaz discaz  25K 11月22日 23:14  gyn2.pt
-rw-r--r-- 1 discaz discaz  43K 11月22日 23:14  gyn-great.pt
-rw-r--r-- 1 discaz discaz  28K 11月22日 23:14  gyn-last.pt
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:56  hanfu-anime-style.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  haruhisky-47000.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:49  henreader.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:57  hiten-style-nao.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:57  hitokomoru-style-nao.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:57  hiyuki-chan.bin
-rw-r--r-- 1 discaz discaz  25K 11月23日 23:35  hutao-prompt-胡桃-yarimasune1-Embeddings.pt
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:57  inuyama-muneto-style-nao.bin
-rw-rw-rw- 1 discaz discaz 106K 11月23日 20:12  Kafuu_Chino_Swimwear.pt
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:13  kanata-hololive.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  kaoming-42600.bin
-rw-r--r-- 1 discaz discaz  49K 10月 6日 19:32  kase-daiki-46506.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:59  kawaii-girl-plus-style-v1-1.bin
-rw-r--r-- 1 discaz discaz  25K 10月 6日 19:32  kazama-iroha-15895.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:59  kogatan-shiny.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:59  kogecha.bin
-rw-r--r-- 1 discaz discaz  49K 11月23日 23:34  kokomi-prompt-珊瑚宫心海-琥鈴琴奏-Embeddings.pt
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  lasterk-24500.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月21日 04:30  learned_embeds.bin
-rw-r--r-- 1 discaz discaz  25K 10月20日 02:13  lucy-cyberpunk.bin
-rw-r--r-- 1 discaz discaz 243K 11月24日 19:02  luotianyi-v2-0c5e7c.webp
-rw-r--r-- 1 discaz discaz  10K 11月23日 23:35  luotianyi_v2-洛天依-Fixing_And_Repairing-Embeddings.pt
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  mana-100000.bin
-rwxrwx--- 1 discaz discaz  49K 10月21日 05:08  maodoufu.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:13  marine.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  mignon-62500.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:00  million-live-akane-15k.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:00  million-live-akane-3k.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:00  million-live-spade-q-object-3k.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:00  million-live-spade-q-style-3k.bin
-rw-r--r-- 1 discaz discaz  31K 10月27日 22:45  myned.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:00  nazuna.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:01  ohisashiburi-style.bin
-rwxrwx--- 1 discaz discaz  55K 10月21日 05:09  ononoimoko.bin
-rw-r--r-- 1 discaz discaz    0 10月 8日 19:37 'Place Textual Inversion embeddings here.txt'
-rw-r--r-- 1 discaz discaz  49K 11月23日 23:40  puno.pt
-rw-r--r-- 1 discaz discaz 4.0K 11月23日 23:33 'raiden shogun-雷电将军-舞晗坤-Embedding-5000.pt'
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:48  raita.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:48 'real xxiii.bin'
-rw-r--r-- 1 discaz discaz  28K 11月22日 01:06  ruoyin.pt
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:48  rustle.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 01:50  sanna-marin.bin
-rw-r--r-- 1 discaz discaz  51K 10月 6日 19:32  satoshi-urushihara-50000.bin
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:02  shigure-ui-style.bin
-rwxrwx--- 1 discaz discaz  46K 10月21日 05:09  shiratama.bin
-rw-r--r-- 1 discaz discaz  40K 11月22日 23:14  sshly-i2i.pt
-rw-r--r-- 1 discaz discaz  40K 11月22日 23:14  sshly-ori.pt
-rw-r--r-- 1 discaz discaz  73K 11月13日 03:09  style-as109.pt
-rw-r--r-- 1 discaz discaz  73K 11月13日 03:09  style-donadona.pt
-rw-r--r-- 1 discaz discaz  61K 11月13日 03:09  style-gbf.pt
-rw-r--r-- 1 discaz discaz  73K 11月13日 03:09  style-kedama.pt
-rw-r--r-- 1 discaz discaz  73K 11月13日 03:09  style-KeiginAlumi_A.pt
-rw-r--r-- 1 discaz discaz  61K 11月13日 03:09  style-keta-nsfw.pt
-rw-r--r-- 1 discaz discaz  61K 11月13日 03:09  style-keta.pt
-rw-r--r-- 1 discaz discaz  73K 11月13日 03:09  style-torino.pt
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:13  suisei-hololive.bin
-rw-r--r-- 1 discaz discaz  49K 10月 6日 19:32  taiga-38567.bin
-rw-rw-rw- 1 discaz discaz  43K 11月23日 20:12  Tashkent.pt
-rw-r--r-- 1 discaz discaz  27K 10月20日 01:52 'Usada Pekora.bin'
-rw-r--r-- 1 discaz discaz 3.8K 10月20日 02:03  wlop-style.bin
-rwxrwx--- 1 discaz discaz  73K 10月21日 05:08  wunei.bin
-rw-r--r-- 1 discaz discaz  43K 11月22日 01:06  ydssx.pt
-rw-r--r-- 1 discaz discaz  22K 10月27日 22:45  YiLeiNa.bin
-rw-r--r-- 1 discaz discaz  28K 11月22日 01:06  yileina.pt
```

**Comment by uikino** [comment]
embedding保存方式用了两种，wget下载链接和浏览器打开右键另存为

**Comment by wfjsw** [comment]
`luotianyi-v2-0c5e7c.webp` 这个文件是我关闭 issue 之前下的还是之后下的？如果是之后下的话，看到 Embeddings 下拉框右边有个刷新按钮，刷一下，再找找

**Comment by wfjsw** [comment]
哦我是不是又做了个有问题的文件

**Comment by uikino** [comment]
理论上能够被webui的话应该能够被视作压缩包打开，你看看生成webp后能不能使用7z打开？这个是在Linux上，所以压缩工具有点特别
![Uploading 2022-11-24 20-42-19 创建的截图.png…]()

**Comment by uikino** [comment]
![2022-11-24 20-42-19 创建的截图](https://user-images.githubusercontent.com/12792786/203787300-66f56411-74ba-4983-944f-16a7ce99125b.png)

**Comment by wfjsw** [comment]
webp/png/dxif/jxf 是四类特殊格式，他们的 embedding 数据是存在 pnginfo 里的，并不是个 pt 文件套壳。
用图片浏览器打开图片会看到图片两边有黑白点，也是存储模型数据的一种方式。
解析这种格式不需要 unpickle，因此比 pt 文件更加安全。

但是 webui 在解析这类文件的时候会让模型内嵌的 `name` 发挥作用。pt 文件虽然也含有这个 `name` 项，但是他不管用。现在我要再重新生成一次所有 embedding 把这个 `name` 项给拔掉。早上生成的那一次没拔干净。

**Comment by uikino** [comment]
哦，长知识了。我还以为和png嵌入方式不一样

**Comment by uikino** [comment]
转换脚本已经写好了，在你的colab的脚本上修改的，我能够发上来吗？这个脚本是将webp还原为pt。但是pt有点不安全啊

**Comment by wfjsw** [comment]
这个东西我用不到，你要发的话自己找个地方发吧

**Comment by uikino** [comment]
那就保留着吧，如果这个issue我不是孤例的话后面在gist上发

**Comment by wfjsw** [comment]
这倒不是你的问题，是文件的问题。挂着等所有文件重制完。
